#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# displays the information about the subdomains

if [ "$#" -eq 1 ]; then
    dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk ' {print "The subdomain www is a "$4" record and points to "$5""}' | tail -n 1
    dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk ' {print "The subdomain lb-01 is a "$4" record and points to "$5""}' | tail -n 1
    dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk ' {print "The subdomain web-01 is a "$4" record and points to "$5""}' | tail -n 1
    dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk ' {print "The subdomain web-02 is a "$4" record and points to "$5""}' | tail -n 1
elif [ "$#" -eq 2 ]; then
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk ' {print "The subdomain "$2" is a "$4" record and points to "$5""}' | tail -n 1
else
    echo "Usage: $0 <domain> [<subdomain>]"
fi
