#!/usr/bin/env bash
# installing  Nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mv /var/www/html/index.nginx-debian.html /var/www/html/save_index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
