#!/usr/bin/env bash
# Requirements:
#    Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee -a /var/www/html/index.html
sudo service nginx start
