#!/usr/bin/env bash
# installs Nginx server, redirects /redirect_me and customizes 404 not found

sudo apt-get -y update
sudo apt install -y nginx

echo"Hello Word!" | sudo tee /var/www/html/

sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/error404.html
sudo sed -i '/server_name _;/a\\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
