#!/usr/bin/env bash
#configuring Nginx so that its HTTP response contains a custom header

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-micah.html
echo "next pagee" > /usr/share/nginx/html/404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/micahondiwa permanent;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\custom_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
service nginx start
