#!/usr/bin/env bash
# configures load balancer for the 2 servers

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 110043-web-01 54.162.6.230:80 check\n\tserver 110043-web-02 3.84.168.250:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
