#!/usr/bin/env bash
# configures load balancer for the 2 servers

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver web-01 34.229.67.178 check\n\tserver web-02 35.175.129.69 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
