#!/usr/bin/env bash
# configures load balancer for the 2 servers

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 110043-web-01 54.162.6.230:80 check\n\tserver 110043-web-02 3.84.168.250:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
