#!/usr/bin/env bash
# sets the port 80

sudo sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
sudo pgrep nginx -o > /run/nginx.pid
sudo nginx -s reload
sudo echo '' > /run/nginx.pid
