#!/usr/bin/env bash
# sets the port 80, and nginx must be running

sudo apt-get update
sudo apt-get install nginx
sudo systemctl start nginx
sudo netstat -an | grep :80
sudo nano /etc/nginx/nginx.conf
sudo systemctl restart nginx
sudo netstat -an | grep :80
sudo firewall-cmd --zone=public --add-port=80/tcp --permanent
sudo firewall-cmd --reload
sudo service nginx restart
