#!/usr/bin/env bash
# Check if file exists
if [ -e "school" ]; then
  echo "school file exists"
else
  echo "school file does not exist"
  exit 1
fi
#Checks if file is empty
if [ ! -s "school" ]; then
  echo "school file is empty"
else
  echo "school file is not empty"
fi

# Check if file is a regular file
if [ -f "school" ]; then
  echo "school is a regular file"
fi
